### ISSUE TITLE
Support excluding or including API and type definitions based on pre-defined annotations

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elasticsearch-specification#2107]
## Feature Proposal

Add support for new JSDoc annotations on API endpoints and individual properties based on which API surface includes/excludes the feature being annotated. The proposed annotations would be `@include_if` and `@exclude_if` which each take a list of annotation names (ie `serverless`, `serverless-public`, `stack`)

Then the compiler can be called with an option `--annotations` with the same annotation names (ie `compiler --annotations serverless serverless-public` would generate the `schema.json` for public Serverless Elasticsearch API).

The motivation for doing this is to continue to have a strong cohesion between Stack and Serverless API surfaces while allowing for small altercations depending on the service.

The new JSDocs tags will be applicable to API endpoints and properties, implemented in that order, in order for other teams to start adding these annotations to APIs they own.

These annotations will not manifest in the `schema.json` output as new fields, instead the types and APIs will be modified so that client generators don't need to be aware of these differences.

## Example

Example that is only available internally for Serverless and publicly for Stack Elasticsearch.

```ts
/**
 * @rest_spec_name example
 * @since 0.0.0
 * @stability stable
 * @exclude_if serverless-public
 */
export interface Request {}
```

Example of an API that is only available on Stack Elasticsearch.

```ts
/**
 * @rest_spec_name example
 * @since 0.0.0
 * @stability stable
 * @exclude_if serverless
 */
export interface Request {}
```

Example that is only available on Serverless Elasticsearch

```ts
/**
 * @rest_spec_name example
 * @since 0.0.0
 * @stability stable
 * @include_if serverless
 */
export interface Request {}
```

Example of a property that is only available on Stack Elasticsearch

```ts
export interface Request {
  query_parameters: {
    /**
     * @exclude_if serverless
     */
    preference?: string
  }
}
```

**Comment by tvernum** [comment]
A few thoughts:

`include_if` feels weird to me because the spec should describe the API rather than the code generation process. That is, I feel like we want to say _this request is `available_in serverless` rather than `include_if serverless`.

If also find it weird that we'll have a `@visibility` annotation that only means something on stack (because serverless visibility is handled by these new tags instead). 
Likewise `@since` will be weird on serverless - if there's a serverless only API what does `@since` mean?

I wonder whether we'll ever have a need for other annotations to have different values on serverless. For example I suspect we could need to have different `@stability` (an API that is stable on serverles but not yet GA in stack).

**Comment by swallez** [comment]
> These annotations will not manifest in the schema.json output as new fields

They should. This is valuable metadata and some generators will need them. In Rust there will be a single code base for all clients, and users will use [Rust's "features"](https://doc.rust-lang.org/cargo/reference/features.html) to choose what variant(s) they want to enable. This is a common practice for optional features and [we already use it](https://github.com/elastic/elasticsearch-rs#features).

Continuing on @tvernum's comment, I agree that the semantics should be descriptive more than imperative. If we also factor in the fact that `since` and `stability` depend on the target environment, what about the following annotation:

```
@availability stack 8.7.0 experimental
@availability serverless 2023-05-04
@availability internal
```

The annotation can be defined multiple times and is defined as `@availability <target> <version>? <stability>?`. Only the target environment is required, version is optional (it's there essentially for documentation purpose, so may also be useful for serverless). Stability is also optional and defaults to `stable`.


This would then be output in `schema.json` as a new property on endpoints and properties in , e.g. 

```json
"availability": [
  "stack": { "since": "8.7.0", "stability": "experimental" },
  "serverless": { "since": "2023-05-04" },
  "internal": {}
]
```

It there's no `@availability` annotation, the endpoint or property is available in all environments. We can keep the existing `@stability` and `@since` annotations and output them in `schema.json` either as they are today, or as the availability of a buit-in `_all` target. They're actually "pre-serverless" information, again for documentation purposes.

**Comment by Anaethelion** [comment]
To iterate on @swallez proposal, I agree with the schema output and general idea of an explicit include mechanism.
This offers more flexibility and allows the compiler to generate many permutations for all targets depending on their needs.

One availability per line seems very well suited for endpoints inclusions but could become verbose and hard to read when it comes to query parameters and fields in classes.
In that spirit I'd like to propose a simplification in the form of a one liner for the `@availability` tag for the sake of readability:

`@availability [stack 8.7.0 experimental], [serverless 2023-05-04]`

**Comment by sethmlarson** [comment]
Thanks all for the comments, agreed that `@since`, `@visibility`, and `@stability` all have implications on Serverless versus Stack Elasticsearch. Here's my thinking:

- ++ on different stabilities on Serverless versus Stack
- `@since` doesn't make sense for Serverless, let's move that to be stack-only as is suggested.
- I'd like to avoid using "positional" arguments for these values both because the values have no meaning without the name, we already do key-value pairs for internal/external tags so let's use that same functionality for this? (`@availability stack since=8.7.0 stability=stable`)
- Internal as its own availability group I am unsure of because there are internal/private APIs in both Stack and Serverless and they aren't the same group. Should we keep `visibility` separate and use that to denote internal APIs (with a default value of `public`)? Many APIs which are public on Stack are private on Serverless (ie `cat.allocations`)

```ts
// Meta note: stability defaults to 'stable' and visibility defaults to 'public'.

/**
 * @rest_spec_name cat.allocations
 * @availability stack since=0.0.0
 * @availability serverless visibility=private
 */
export interface Request {}
```

compiles to:

```ts
"availability": {
  "stack": {"since": "0.0.0", "stability": "stable", "visibility": "public"},
  "serverless": {"stability": "stable", "visibility": "public"},
}
```
