### ISSUE TITLE
Doc URL keywords 

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch-specification#714]
## 🚀 Feature Proposal

Hard-coded documentation URLs require maintenance across the specification source files when our URLs change. In Kibana, we use a [documentation link service](https://github.com/elastic/kibana/blob/master/src/core/public/doc_links/doc_links_service.ts) that maps keywords to URLs, so that we can use the keywords within the apps and maintain the full URLs in a single place. A similar keyword<->URL mapping list and support for keywords in the docUrl field and @doc_url comments would be helpful.

In the long run, we might want to move to using primed doc queries instead of linking to specific pages. That could be accomplished within the keyword mapping file too but in the future we might want to consider supporting primed search terms in the docUrl field.

## Motivation

Hardcoded URLs in the spec are subject to link rot and, in the current system, frequent build failures as content moves around.

## Example

Instead of something like this:

> "docUrl": "https://www.elastic.co/guide/en/elasticsearch/reference/current/async-search.html",

or 

>   /**
     *  Boolean) If true, the request is real-time as opposed to near-real-time.
     * @doc_url https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#realtime
     */

... we would ideally have a simple unique keyword (or in the long term, maybe search terms) that is resolved into the appropriate URL as part of the client/docs generation.

**Comment by delvedor** [comment]
Currently, the `docUrl` is being used in many clients, so I would prefer to leave it as is and have a dual solution until the new system is up and running.
How about `docId`?

**Comment by swallez** [comment]
+1 with the addition of a `@doc_id` tag in the TypeScript specification with a similar (or the same?) documentation service as in Kibana, and migrate away from `@doc_url` once it's in place.

The compilation of TypeScript specs to the JSON schema can then produce the same `docUrl` property as today by resolving the `@doc_id` tag if present using the link service.

And in the transition phase from `@doc_url` to `@doc_id`, the compiler can use `@doc_id` if present and fallback to `@doc_url` otherwise.

**Comment by lcawl** [comment]
That sounds reasonable to me, thanks!
